<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace Lm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lm.hello</code>
 */
class hello extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string str = 2;</code>
     */
    private $str = '';
    /**
     * Generated from protobuf field <code>int32 opt = 3;</code>
     */
    private $opt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $str
     *     @type int $opt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Hello::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string str = 2;</code>
     * @return string
     */
    public function getStr()
    {
        return $this->str;
    }

    /**
     * Generated from protobuf field <code>string str = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->str = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 opt = 3;</code>
     * @return int
     */
    public function getOpt()
    {
        return $this->opt;
    }

    /**
     * Generated from protobuf field <code>int32 opt = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOpt($var)
    {
        GPBUtil::checkInt32($var);
        $this->opt = $var;

        return $this;
    }

}

