<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a480a0b68656c6c6f2e70726f746f12026c6d222d0a0568656c6c6f120a" .
            "0a026964180120012805120b0a03737472180220012809120b0a036f7074" .
            "180320012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

