<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcdata.proto

namespace GPBMetadata;

class Rpcdata
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98010a0d727063646174612e70726f746f120772706364656d6f22760a" .
            "0372706312110a097265715f636c61737318022001280912120a0a726571" .
            "5f616374696f6e18032001280912120a0a7265715f706172616d73180420" .
            "01280912100a087265735f6461746118052001280912100a087265735f63" .
            "6f646518062001280512100a087265735f74696d65180720012805620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

